/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:040310673031:userpool/us-east-1_oSzHj7tit",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_oSzHj7tit",
    "aws_user_pools_web_client_id": "6sinbl99e63pvsvif330lhjveo",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_cloud_logic_custom": [
        {
          name: "initialize-user",
          endpoint: "https://zkeuos9g2a.execute-api.us-east-1.amazonaws.com/v1",
          region: "us-east-1"
        }
      ]
};


export default awsmobile;
